### PR TITLE
ojopaul:feature/#584_Subscribers_cant_see_Author_pages

### PR DESCRIPTION
**Pull request by ojopaul**
## Description

Fixed issue with Subscribers authors page post query error #584

## Benefits

Authors other than Administrator will now able to view their posts on authors page both frontend and admin screen

## Applicable issues

https://github.com/publishpress/PublishPress-Authors/issues/584

## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Comment by andergmartins** [comment]
@ojopaul the fix makes sense, but while testing I saw an error message related to the query you modified but I saw it only once and unfortunately I didn't copy the message. Now I can't replicate, but will make more tests to make sure we don't break queries.

**Comment by andergmartins** [comment]
I was able to replicate it logged in as a contributor user, having one post where he is the author, and visiting the author page:

>WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10' at line 2]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_term_taxonomy ON ( wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ((wp_posts.post_type IN ('post') AND (wp_posts.post_status = 'publish' OR ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND wp_posts.post_status = 'private')))) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10

>WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10' at line 2]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_term_taxonomy ON ( wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ((wp_posts.post_type IN ('post') AND (wp_posts.post_status = 'publish' OR ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND wp_posts.post_status = 'private')))) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10

image

**Review by andergmartins — CHANGES_REQUESTED** [review]
@ojopaul I was able to replicate it logged in as a contributor user, having one post where he is the author, and visiting the author page:

>WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10' at line 2]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_term_taxonomy ON ( wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ((wp_posts.post_type IN ('post') AND (wp_posts.post_status = 'publish' OR ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND wp_posts.post_status = 'private')))) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10

>WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10' at line 2]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_term_taxonomy ON ( wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id ) WHERE 1=1 AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND ((wp_posts.post_type IN ('post') AND (wp_posts.post_status = 'publish' OR ( (wp_term_taxonomy.taxonomy = "author" AND wp_term_taxonomy.term_id = '15') ) AND wp_posts.post_status = 'private')))) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 10

image

**Review by agapetry — CHANGES_REQUESTED** [review]
@ojopaul This will need a more targeted solution. Since this function hooks into the 'posts_where' filter, it is likely to encounter some other case of four consecutive parentheses which should not be replaced to three.

**Comment by ojopaul** [comment]
Thanks for the full insight @andergmartins, i investigate the issue further and noticed for user other than admin or without permission to read private post, wordpress add `post_author = %d AND post_status = 'private'` to the post where query. So, i made a commit that first replace post author in private post status context before other author replacement and that fix the issue but i understand my regex may not be solid. So, kindly check and update me if you feel there may be potential problem with third party query.

**Comment by ojopaul** [comment]
Thanks for the full insight @andergmartins, i investigate the issue further and noticed for user other than admin or without permission to read private post, wordpress add post_author = %d AND post_status = 'private' to the post where query. So, i made a commit that first replace post author in private post status context before other author replacement and that fix the issue but i understand my regex may not be solid. So, kindly check and update me if you feel there may be potential problem with third party query.

**Comment by andergmartins** [comment]
@ojopaul I see we have a more specific query replacement now. We can't predict all the possible conflicts with other plugins, but like @agapetry suggested and you did, it seems like  preventing to break the query if other plugin changes it in a way it becomes not compatible with the regex. If that happens, the replacement won't happen, but the query won't broke as well.

I was testing and it is working better now.

**Review by agapetry — APPROVED** [review]

**Review by andergmartins — APPROVED** [review]

**Pull request merged**
