### PR TITLE
Integration with the WordPress Bulk Edit feature for setting post authors

### PR DESCRIPTION
**Pull request by mdmag**
Integration done with some tricks:
1- Initializing the select2 and sortable after clicking "Quick edit"
2- Populating the value of authors for each post into the list.
3- get_multiple_authors function uses cache key and this causes the quick edit to return the previous value after saving. 
I have added another parameter for ignoring cache.

--------
Note: I tried to lint the code according to PSR12 standard and used the composer script "cs-fix" with option --standard= PSR12 and I am not sure it is formatted right or not. Please confirm.

### CODE REVIEW

**Comment by mdmag** [comment]
https://screencast-o-matic.com/watch/cYjIVZGyJ8

**Comment by stevejburge** [comment]
Background from @mdmag 

> PublishPress Authors save the authors of a specific post in a variable so if the function re-called again it gets its result from this variable instead of re-fetching it from DB. The problem with Quick edit is that it depends on ajax and this value needs to be re-fetched every time we call this function. So I added a parameter to this function to ignore this saving and re-fetch the authors every time. 
> 
> Also, the quick edit itself needed multiple workarounds with javascript to make it work properly. To elaborate: initializing select2 and sortable libraries should be on click on quick edit and also I render all authors on click on quick edit then from "Authors" column I get the value for each post, then I iterate over the authors list and got the intersection of their slugs with [migsa, mfbestvpn] which I got from the authors column and remove the rest.

**Comment by andergmartins** [comment]
Thanks @mdmag. Yeah, there was a regression bug when I introduced the cache. I just merged a fix into the development branch. But I will double check your suggestion as well. Thanks for the PR.

**Comment by andergmartins** [comment]
Thanks @mdmag

**Comment by andergmartins** [comment]
@mdmag please, could you check this new issue? #227 
This PR introduced it and I didn't notice that on my review, until today after a user reported the performance downgrade.

**Pull request merged**
